
apiVersion: v1
kind: Pod
metadata:
  name: project1-pod
  labels:
    app: project1
spec:
  containers:
    - name: project1-container
      image: danahmed/project1:latest
      ports:
        - containerPort: 4200

---

apiVersion: v1
kind: Service
metadata:
  name: project1-service
spec:
  selector:
    app: project1
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 4200
      nodePort: 30001
  type: NodePort
