apiVersion: v1
kind: Pod
metadata:
  name: {{ include "myapp.fullname" . }}-pod
  labels:
    app: project1
  {{- include "myapp.labels" . | nindent 4 }}
spec:
  containers:
  - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    name: {{ .Release.Name }}
    ports:
    - containerPort: 4200