apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-service
  labels:
  {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: project1
    {{- include "myapp.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}